name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch currently.
on:
  pull_request:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
      run: echo "$GITHUB_HEAD_REF"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2