name: Deploy Production
# on main branch updates
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
              #install serverless
            - name: Install Serverless Framework
              run: npm install -g serverless
              #install node modules
            - name: Install NPM dependencies
              run: npm install
            - name: Set dev profile
              run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile dev
            - name: Create .aws
              run: |
                ls ~/.aws
                cat ~/.aws/credentials || true
                cat ~/.aws/config || true
              #serverless deploy
            - name: deploy dev
              run: sls deploy --stage dev --aws-profile dev
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

